# Generated by Django 4.1.3 on 2022-11-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todosapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1998-05-20"),
            preserve_default=False,
        ),
    ]
